### ISSUE TITLE
support-cli as its own module?

### ISSUE THREAD

**Issue by smikes** [npm/support-cli#1]
I'm going to completely abuse the issue tracker here and raise this question:

Should there be a support-cli module separate from npm?

Arguments against: more complexity

Argument for: 

suppose a user has a mostly working node but a broken npm, or an old npm (<2.1.9 is old by this standard).  Wouldn't it be nice if there were a "thing that they can do" that does some sniffing around (looking for outdated node, npm version, clean up cache, that sort of stuff) that would **not** require them to be able to upgrade npm (which feels scary to novice users)

Something that they can run via `curl <url> | sh`

**Comment by othiym23** [comment]
That sounds like an excellent project for somebody who has some spare time (hint: not me) to put together! I do want to build out `npm doctor` at some point to detect / fix issues with npm's environment and configuration, but it's entirely possible that that functionality could be pioneered outside of npm itself. I don't think `support-cli` is a very good name for that tool (`npm-doctor` is much better), and I don't think this is the right place to host it.

This repo should be reserved exclusively for support, because I don't want to get back to a situation where we need to worry about giving people privileges to manage issues because we want control over who gets to push code. _Especially_ if we're going to be pushing issues here in a semi-automated way.

**Comment by smikes** [comment]
Agree that project doesn't belong here.
