### ISSUE TITLE
meta: labels

### ISSUE THREAD

**Issue by kenany** [npm/support-cli#2]
I've taken the liberty of bringing over some of the labels used in `npm/npm`:
- `dedupe`
- `lifecycle`
- `node-bug`
- `peerdependencies`
- `registry`
- `shasum`
- `shrinkwrap`
- `windows`
- `yeoman`

I also changed the color of `bug` to that of `npm/npm`'s.

I think the following default labels could be removed, what do ya'll think?:
- `enhancement`, anything that needs this should be in `npm/npm`
- `help wanted`, basically `patch-welcome`; again: belongs in `npm/npm`
- `invalid`, would anyone open something "invalid" here?
- `question`, questions about `npm` should probably go in `npm/npm`?
- `wontfix`, not sure about this one

**Comment by othiym23** [comment]
Nuke all the default labels. My default approach would be to start without any labels at all, and create them as we need them – you've probably noticed my tendency to unsentimentally nuke labels from npm/npm whenever I think they're no longer serving a useful purpose.

Anything labeled `bug` should probably be closed here and opened as an issue on npm/npm. The goal of this repo is to handle support requests. It's probably inevitable that it will turn into a bikeshedding forum for feature requests as well, because yesterday's support ticket turns into today's missing feature, but once something has been confirmed as a bug, it belongs on the primary repo.

**Comment by smikes** [comment]
> once something has been confirmed as a bug, it belongs on the primary repo.

+1

I have no opinion about github labels yet.  Working on the contributing page ( https://github.com/npm/support-cli/blob/master/CONTRIBUTING.md )

**Comment by kenany** [comment]
Alright, we'll start from a clean slate and add labels as needed :)
